source 'https://rubygems.org'

gem 'appium_console'
gem 'appium_lib'
gem 'cucumber'
gem 'lefthook'
gem 'nokogiri'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'test-unit'
gem 'semantic_logger'
gem 'slowhandcuke'
